/* TermInfo */
create table TermInfo (
  RefId VARCHAR(36) PRIMARY KEY,
  SchoolInfo_RefId VARCHAR(36) DEFAULT NULL,
  SchoolYear VARCHAR(200) DEFAULT NULL,
  StartDate VARCHAR(200) DEFAULT NULL,
  EndDate VARCHAR(200) DEFAULT NULL,
  Description VARCHAR(2000) DEFAULT NULL,
  RelativeDuration VARCHAR(200) DEFAULT NULL,
  TermCode VARCHAR(200) DEFAULT NULL,
  Track VARCHAR(200) DEFAULT NULL,
  TermSpan VARCHAR(200) DEFAULT NULL,
  MarkingTerm VARCHAR(200) DEFAULT NULL,
  SchedulingTerm VARCHAR(200) DEFAULT NULL,
  AttendanceTerm VARCHAR(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
